name: Build Test Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Print softuni usernme
      run: echo 'ilianachakarova'

  build-and-ui-test:
   needs: build-and-unit-test  
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install   
    - name: Start server
      run: npm run start &
    - name: Execute ui tests
      run: npm run test:ui

  deploy_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build-and-ui-test
    steps:
          - name: Deploy to production
            uses: johnbeynon/render-deploy-action@v0.0.8
            with:
              service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
              api-key: ${{ secrets.MY_RENDER_API_KEY }}        
