name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Execute unit tests
      run: npm run test:unit
    - name: Print softuni usernme
      run: echo 'ilianachakarova'

  build-and-ui-test:
   needs: build-and-unit-test 
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Install playwright browsers
      run: npx playwright install   
    - name: Start server
      run: npm start
    - name: Execute ui tests
      run: npm run test:ui    
